# Generated by Django 5.0.3 on 2024-04-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abdPain', models.JSONField(blank=True, default=list)),
                ('anemmia', models.JSONField(blank=True, default=list)),
                ('vomit', models.JSONField(blank=True, default=list)),
                ('diarhea', models.JSONField(blank=True, default=list)),
                ('bmi', models.JSONField(blank=True, default=list)),
                ('weightLoss', models.JSONField(blank=True, default=list)),
                ('cdsAnalysis', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
