# Generated by Django 5.0.3 on 2024-04-17 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('bloodgroup', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('cpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abdPain', models.JSONField(blank=True, default=list)),
                ('anemmia', models.JSONField(blank=True, default=list)),
                ('vomit', models.JSONField(blank=True, default=list)),
                ('diarhea', models.JSONField(blank=True, default=list)),
                ('bmi', models.JSONField(blank=True, default=list)),
                ('cdsAnalysis', models.JSONField(blank=True, default=list)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.signup')),
            ],
        ),
    ]
